homework_05/__init__.py
from . import app

__all__ = [
    "app",
]

homework_05/app.py
"""
Домашнее задание №5
Первое веб-приложение

создайте базовое приложение на Flask
создайте index view /
добавьте страницу /about/, добавьте туда текст
создайте базовый шаблон (используйте https://getbootstrap.com/docs/5.0/getting-started/introduction/#starter-template)
в базовый шаблон подключите статику Bootstrap 5 и добавьте стили, примените их
в базовый шаблон добавьте навигационную панель nav (https://getbootstrap.com/docs/5.0/components/navbar/)
в навигационную панель добавьте ссылки на главную страницу / и на страницу /about/ при помощи url_for
"""

from flask import Flask

from .views.about import about_app
from .views.home import home_app

app = Flask(__name__)

app.register_blueprint(about_app, url_prefix="/about")

app.register_blueprint(home_app, url_prefix="/")

homework_05/views/about.py
from flask import (
    Blueprint,
    render_template,
)

about_app = Blueprint("about_app", __name__)

@about_app.get("/", endpoint="about_page")
def about_page():
    return render_template("pages/about.html")

homework_05/views/home.py
from flask import (
    Blueprint,
    render_template,
)

home_app = Blueprint("home_app", __name__)

@home_app.get("/", endpoint="home_page")
def home_page():
    return render_template("pages/home.html")

homework_05/templates/base.html
<!doctype html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>
        {% block title %}
            Base title
        {% endblock %}
    </title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a href="{{ url_for('home_app.home_page') }}">
          <button class="btn btn-secondary btn-sm" type="button" >Home</button>
        </a>
      </div>

      <div class="container-fluid">
          <a href="{{ url_for('about_app.about_page') }}">
            <button type="button" class="btn btn-info btn-sm">About</button>
          </a>     
      </div>
    </nav>

    {% block body %}
        Base body
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

  </body>
</html>

homework_05/templates/pages/about.html
{% extends 'base.html' %}

{% block title %}
About the Python
{% endblock %}

{% block body %}

    Python is powerful!

{% endblock %}

homework_05/templates/pages/home.html
{% extends 'base.html' %}

{% block title %}
Home page
{% endblock %}

{% block body %}

    Hello, the students!

{% endblock %}